### ISSUE TITLE
偶尔会报错

### ISSUE THREAD

**Issue by SanaChitose** [SonderXiaoming/portune#1]
![图片](https://user-images.githubusercontent.com/102790983/186105319-f2f5cd08-dc99-4ea5-9ce2-67813bd78dc9.png)
看不出来原因、也不是100%复现的，只能来大佬这提issue了

**Comment by SonderXiaoming** [comment]
艹，没看见（我也不知道为什么）

**Comment by cpms** [comment]
```
[2022-10-12 23:08:42,020 portune] ERROR: <class 'ValueError'> occured when portune handling message -1187985357.
[2022-10-12 23:08:42,020 portune] ERROR: the msg argument is not recognized
Traceback (most recent call last):
  File "/root/xcwbot/HoshinoBot/hoshino/msghandler.py", line 21, in handle_message
    await service_func.func(bot, event)
  File "/root/xcwbot/HoshinoBot/hoshino/modules/portune/portune.py", line 50, in portune
    await bot.send(ev, pic, at_sender=True)
  File "/usr/local/lib/python3.10/site-packages/aiocqhttp/__init__.py", line 249, in send
    msg = message if isinstance(message, Message) else Message(message)
  File "/usr/local/lib/python3.10/site-packages/aiocqhttp/message.py", line 415, in __init__
    raise ValueError('the msg argument is not recognized')
ValueError: the msg argument is not recognized
```

我这里也偶尔会出现（某些日子，某些人发的，结果就是机器人没回复）。好像没啥规律，很难复现，可能同一个人第二天又可以了

**Comment by SonderXiaoming** [comment]
只能等大佬看见修了
